version: '3.7'

networks:
  proxynet:
    name: idev
    external: true

services:
  pgadmingui:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - 9080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: EvolvePG4
    networks:
      - proxynet
