version: '3.7'

networks:
  proxynet:
    name: idev
    external: true

services:
  adminergui:
    build: .
    container_name: adminer4.7
    restart: always
    ports:
      - 9090:8080
    environment:
      # - ADMINER_DEFAULT_SERVER=database
      - ADMINER_PLUGINS=tables-filter dump-date dump-json dump-xml dump-zip
      - ADMINER_DESIGN=pepa-linha
    networks:
      - proxynet
