version: '3.7'

volumes:
  psql:
    external: true

networks:
  proxynet:
    name: idev
    external: true

services:
  dbpsql:
    build: .
    container_name: psqlv12
    restart: always
    environment:
      POSTGRES_PASSWORD: SQL085bc2
    networks:
      - proxynet
    ports:
      - 5432:5432
    restart: always
    volumes:
      # save your .sql files to the `Queries` dir
      - $HOME/Queries:/queries
      - psql:/var/lib/postgresql/data:consistent
